/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.Telas;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.example.ProdutoDAO;

/**
 *
 * @author 04404465033
 */
public class MenuPrincipalSwing extends javax.swing.JFrame {
    
    private AdicionarProdutoSwing adicionarProduto;
    private LerProdutosSwing lerProdutos;
    private ProdutoDAO prodDao;
    private EditarProdutoSwing editarProduto;
    private ApagarProdutoSwing apagarProduto;
    /**
     * Creates new form NewJFrame
     */
    public MenuPrincipalSwing(){
        try {
            adicionarProduto = new AdicionarProdutoSwing();
            lerProdutos = new LerProdutosSwing();
            prodDao = new ProdutoDAO();
            editarProduto = new EditarProdutoSwing(prodDao.lerProduto());
            apagarProduto = new ApagarProdutoSwing(prodDao.lerProduto());
            initComponents();
        } catch (SQLException ex) {
            System.getLogger(MenuPrincipalSwing.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnProdutos = new javax.swing.JMenu();
        miAdicionar = new javax.swing.JMenuItem();
        miEditar = new javax.swing.JMenuItem();
        miLer = new javax.swing.JMenuItem();
        mnDeletar = new javax.swing.JMenu();
        miApagarUm = new javax.swing.JMenuItem();
        miApagarTodos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Produtos");

        mnProdutos.setText("Produtos");

        miAdicionar.setText("Adicionar");
        miAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAdicionarActionPerformed(evt);
            }
        });
        mnProdutos.add(miAdicionar);

        miEditar.setText("Editar");
        miEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarActionPerformed(evt);
            }
        });
        mnProdutos.add(miEditar);

        miLer.setText("Ler");
        miLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLerActionPerformed(evt);
            }
        });
        mnProdutos.add(miLer);

        jMenuBar1.add(mnProdutos);

        mnDeletar.setText("Deletar");

        miApagarUm.setText("Apagar um Produto");
        miApagarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miApagarUmActionPerformed(evt);
            }
        });
        mnDeletar.add(miApagarUm);

        miApagarTodos.setText("Apagar Banco");
        miApagarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miApagarTodosActionPerformed(evt);
            }
        });
        mnDeletar.add(miApagarTodos);

        jMenuBar1.add(mnDeletar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAdicionarActionPerformed
        adicionarProduto.setVisible(true);
    }//GEN-LAST:event_miAdicionarActionPerformed

    private void miLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLerActionPerformed
        lerProdutos.setVisible(true);
    }//GEN-LAST:event_miLerActionPerformed

    private void miApagarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miApagarTodosActionPerformed
        try {
            String[] options = {"Sim", "Não"};
            int selection = JOptionPane.showOptionDialog(null, "Deseja excluir o banco de dados?", "Excluir Banco de Dados", WIDTH, HEIGHT, null, options, options[1]);
            switch (selection){
                case 0:
                    prodDao.deleteAll();
                    JOptionPane.showMessageDialog(null, "Banco de Dados Excluído com Sucesso!", "Banco Excluído", 1);
            }
        } catch (SQLException ex) {
            System.getLogger(MenuPrincipalSwing.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }     
    }//GEN-LAST:event_miApagarTodosActionPerformed

    private void miEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarActionPerformed
        editarProduto.setVisible(true);
    }//GEN-LAST:event_miEditarActionPerformed

    private void miApagarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miApagarUmActionPerformed
        apagarProduto.setVisible(true);
    }//GEN-LAST:event_miApagarUmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAdicionar;
    private javax.swing.JMenuItem miApagarTodos;
    private javax.swing.JMenuItem miApagarUm;
    private javax.swing.JMenuItem miEditar;
    private javax.swing.JMenuItem miLer;
    private javax.swing.JMenu mnDeletar;
    private javax.swing.JMenu mnProdutos;
    // End of variables declaration//GEN-END:variables
}
