/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import modelo.Categoria;
import modelo.Produto;

/**
 *
 * @author mateu
 */
public class SistemaVendasView extends javax.swing.JFrame {
    
    private ArrayList<Categoria> categorias;
    private ArrayList<Produto> produtos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SistemaVendasView.class.getName());

    /**
     * Creates new form SistemaVendasView
     */
    public SistemaVendasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mbSistemaVendas = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroProduto = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        miRelatorioCategoria = new javax.swing.JMenuItem();
        miRelatorioProduto = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        mnCadastro.setText("Cadastro");

        miCadastroCategoria.setText("Categoria");
        mnCadastro.add(miCadastroCategoria);

        miCadastroProduto.setText("Produto");
        mnCadastro.add(miCadastroProduto);

        mbSistemaVendas.add(mnCadastro);

        mnRelatorio.setText("Relatório");

        miRelatorioCategoria.setText("Categoria");
        mnRelatorio.add(miRelatorioCategoria);

        miRelatorioProduto.setText("Produto");
        mnRelatorio.add(miRelatorioProduto);

        mbSistemaVendas.add(mnRelatorio);

        setJMenuBar(mbSistemaVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SistemaVendasView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mbSistemaVendas;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroProduto;
    private javax.swing.JMenuItem miRelatorioCategoria;
    private javax.swing.JMenuItem miRelatorioProduto;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnRelatorio;
    // End of variables declaration//GEN-END:variables
}
