/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aula05.Telas;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author 04404465033
 */
public class Exercicio4Swing extends javax.swing.JFrame {
    private JPanel painelDinamico;
    private JTextField[] textField;
    private JLabel[] label;
    private JTextArea textArea;
    private int quantidadeNotas;
    
    /**
     * Creates new form Exercicio4Swing
     */
    public Exercicio4Swing() {
        initComponents();
        btSalvar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbQuantNotas = new javax.swing.JLabel();
        tfQuantNotas = new javax.swing.JTextField();
        btContinuar = new javax.swing.JButton();
        pnPainelDinamico = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exercício 4");

        lbQuantNotas.setText("Digite a quantidade de notas:");

        btContinuar.setText("Continuar");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });

        pnPainelDinamico.setLayout(new java.awt.BorderLayout());

        btSalvar.setText("Calcular");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btContinuar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbQuantNotas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(pnPainelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantNotas)
                    .addComponent(tfQuantNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btContinuar)
                    .addComponent(btSalvar))
                .addGap(18, 18, 18)
                .addComponent(pnPainelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        try{
            if (pnPainelDinamico != null) {
            pnPainelDinamico.removeAll();
            }
            quantidadeNotas = Integer.parseInt(tfQuantNotas.getText());
            painelDinamico = new JPanel(new java.awt.GridLayout(quantidadeNotas + 1, 2, 5, 5));
            textField = new JTextField[quantidadeNotas];
            label = new JLabel[quantidadeNotas];
            textArea = new JTextArea();
            textArea.setEditable(false);

            for(int i = 0; i<quantidadeNotas; i++){
                label[i] = new JLabel("Digite a nota " + (i+1));
                textField[i] = new JTextField("");

                painelDinamico.add(label[i]);
                painelDinamico.add(textField[i]);
            }
            painelDinamico.add(textArea);
            pnPainelDinamico.add(painelDinamico);
            pnPainelDinamico.revalidate();
            pnPainelDinamico.repaint();
            this.pack();
            btSalvar.setVisible(true);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
            
    }//GEN-LAST:event_btContinuarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try{
            int quantCamposFalhos = 0;
            double media = 0;
            for(int i = 0; i< this.quantidadeNotas; i++){
                if(!(this.textField[i].getText().equals("")) && (Double.parseDouble(this.textField[i].getText()) >=0 && (Double.parseDouble(this.textField[i].getText())) <=10 )){
                    media += Double.parseDouble(this.textField[i].getText());
                }
                else{
                    JOptionPane.showMessageDialog(null, "Nota " + (i+1) + " não registrada");
                    quantCamposFalhos++;
                }   
            }
            if(quantCamposFalhos>0){
                this.textArea.setText("Falha ao calcular a média");
            }
            else{
                media = media/this.quantidadeNotas;
                if(media>7){
                    this.textArea.setText("Media: " + media + ". Aprovado!");
                }
                else{
                    this.textArea.setText("Media: " + media + ". Reprovado!");
                }
                
            }
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
            
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContinuar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel lbQuantNotas;
    private javax.swing.JPanel pnPainelDinamico;
    private javax.swing.JTextField tfQuantNotas;
    // End of variables declaration//GEN-END:variables
}
