/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aula05.Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author mateu
 */
public class Exercicio6Swing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Exercicio6Swing.class.getName());
    private String[] aux;
    private int[] num;
    /**
     * Creates new form Exercicio6Swing
     */
    public Exercicio6Swing() {
        initComponents();
        aux = new String[5];
        num = new int[5]; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNumeros = new javax.swing.JLabel();
        tfNumeros = new javax.swing.JTextField();
        btContinuar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exercício 6");

        lbNumeros.setText("Digite os numeros separados por ';' :");

        btContinuar.setText("Continuar");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });

        taRelatorio.setEditable(false);
        taRelatorio.setColumns(20);
        taRelatorio.setRows(5);
        jScrollPane1.setViewportView(taRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btContinuar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbNumeros)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeros)
                    .addComponent(tfNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btContinuar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        try{
            this.aux = tfNumeros.getText().split(";"); 
            if(this.aux.length!=5){
                JOptionPane.showMessageDialog(null, "Quantidade de numeros diferente de 5");
            }
            else{
                int cont = 0;
                for(int i = 0; i<5; i++){
                    this.num[i] = Integer.parseInt(aux[i]);
                }
                for(int i = 0; i<5; i++){
                    for(int c = 0; c<4;c++){
                        if(this.num[c]>this.num[c+1]){
                            cont = num[c];
                            num[c] = num[c+1];
                            num[c+1] = cont;
                        }
                    }
                }
                taRelatorio.setText("Numeros em ordem: ");
                for(int i = 0; i<5; i++){
                    if(i!=4){
                        taRelatorio.append(num[i] + ", ");
                    }
                    else{
                        taRelatorio.append(num[i] + "");
                    }
                }
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btContinuarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContinuar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNumeros;
    private javax.swing.JTextArea taRelatorio;
    private javax.swing.JTextField tfNumeros;
    // End of variables declaration//GEN-END:variables
}
