/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aula05.Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author mateu
 */
public class Exercicio5Swing extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Exercicio5Swing.class.getName());
    private String[] aux;
    private int[] notas;
    /**
     * Creates new form Exercício5Swing
     */
    public Exercicio5Swing() {
        initComponents();
        aux = new String[5];
        notas = new int[5];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNotas = new javax.swing.JLabel();
        tfNotas = new javax.swing.JTextField();
        btContinuar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exercício 5");

        lbNotas.setText("Digite as notas (separadas por ';') :");

        btContinuar.setText("Continuar");
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });

        taRelatorio.setEditable(false);
        taRelatorio.setColumns(20);
        taRelatorio.setRows(5);
        jScrollPane1.setViewportView(taRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btContinuar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNotas)
                        .addGap(18, 18, 18)
                        .addComponent(tfNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNotas)
                    .addComponent(tfNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btContinuar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        try{
            int maior = Integer.MIN_VALUE;
            int menor = Integer.MAX_VALUE;
            this.aux = tfNotas.getText().split(";"); 
            if(this.aux.length!=5){
                JOptionPane.showMessageDialog(null, "Quantidade de numeros diferente de 5");
            }
            else{
                for(int i = 0; i<5; i++){
                    this.notas[i] = Integer.parseInt(aux[i]);
                    if(this.notas[i]>maior){
                        maior = this.notas[i];
                    }
                    if(this.notas[i]<menor){
                        menor = this.notas[i];
                    }
                }
                taRelatorio.setText("A maior nota é: " + maior + "\nA menor nota é: " + menor);
            }     
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btContinuarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContinuar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNotas;
    private javax.swing.JTextArea taRelatorio;
    private javax.swing.JTextField tfNotas;
    // End of variables declaration//GEN-END:variables
}
