/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aula05.Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author 04404465033
 */
public class MenuPrincipalSwing extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalSwing
     */
    Exercicio1Swing ex1 = new Exercicio1Swing();
    Exercicio2Swing ex2 = new Exercicio2Swing();
    Exercicio3Swing ex3 = new Exercicio3Swing();
    Exercicio4Swing ex4 = new Exercicio4Swing();
    Exercicio5Swing ex5 = new Exercicio5Swing();
    Exercicio6Swing ex6 = new Exercicio6Swing();
    
    public MenuPrincipalSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgExercicios = new javax.swing.ButtonGroup();
        lbTexto1 = new javax.swing.JLabel();
        lbTexto2 = new javax.swing.JLabel();
        rbEx1 = new javax.swing.JRadioButton();
        rbEx2 = new javax.swing.JRadioButton();
        rbEx3 = new javax.swing.JRadioButton();
        rbEx4 = new javax.swing.JRadioButton();
        rbEx5 = new javax.swing.JRadioButton();
        rbEx6 = new javax.swing.JRadioButton();
        btAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atividade Aula 04/09");

        lbTexto1.setText("Bem Vindo ao Programa!");

        lbTexto2.setText("Qual exercício deseja visualizar?");

        bgExercicios.add(rbEx1);
        rbEx1.setText("Exercício 1");

        bgExercicios.add(rbEx2);
        rbEx2.setText("Exercício 2");

        bgExercicios.add(rbEx3);
        rbEx3.setText("Exercício 3");

        bgExercicios.add(rbEx4);
        rbEx4.setText("Exercício 4");

        bgExercicios.add(rbEx5);
        rbEx5.setText("Exercício 5");

        bgExercicios.add(rbEx6);
        rbEx6.setText("Exercício 6");

        btAbrir.setText("Abrir");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lbTexto1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lbTexto2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbEx1)
                        .addGap(18, 18, 18)
                        .addComponent(rbEx2)
                        .addGap(18, 18, 18)
                        .addComponent(rbEx3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbEx4)
                        .addGap(18, 18, 18)
                        .addComponent(rbEx5)
                        .addGap(18, 18, 18)
                        .addComponent(rbEx6)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTexto2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEx1)
                    .addComponent(rbEx2)
                    .addComponent(rbEx3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEx4)
                    .addComponent(rbEx5)
                    .addComponent(rbEx6))
                .addGap(18, 18, 18)
                .addComponent(btAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        if(rbEx1.isSelected()){
            ex1.setVisible(true);
        }
        else if(rbEx2.isSelected()){
            ex2.setVisible(true);        
        }
        else if(rbEx3.isSelected()){
            ex3.setVisible(true);        
        }
        else if(rbEx4.isSelected()){
            ex4.setVisible(true);        
        }
        else if(rbEx5.isSelected()){
            ex5.setVisible(true);        
        }
        else if(rbEx6.isSelected()){
            ex6.setVisible(true);        
        }
    }//GEN-LAST:event_btAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgExercicios;
    private javax.swing.JButton btAbrir;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JRadioButton rbEx1;
    private javax.swing.JRadioButton rbEx2;
    private javax.swing.JRadioButton rbEx3;
    private javax.swing.JRadioButton rbEx4;
    private javax.swing.JRadioButton rbEx5;
    private javax.swing.JRadioButton rbEx6;
    // End of variables declaration//GEN-END:variables
}
